Verify that pipeline_spec is a dictionary object
Cause a TypeError at `"pipelineSpec" in pipeline_spec` if the pipeline
file is empty.

> TypeError: argument of type 'NoneType' is not iterable