Revert "Explicitly specify the type of PathLike"
This reverts commit b6395ecae06b8d113119dfe585617d67c42390f5.

Python 3.7 cannot handle `PathLike[str]`.
TypeError: 'ABCMeta' object is not subscriptable